---
version: "3.8"

services:
  server01:
    image: distribuidos:dev
    build: .
    command:
      - -v=debug
      - --peer=server02:50051
      - --peer=server03:50051
      - --peer=server04:50051
      - --peer=server05:50051
    ports:
      - 50051:50051
  server02:
    image: distribuidos:dev
    build: .
    command:
      - -v=debug
      - --peer=server01:50051
      - --peer=server03:50051
      - --peer=server04:50051
      - --peer=server05:50051
    ports:
      - 50052:50051
  server03:
    image: distribuidos:dev
    build: .
    command:
      - -v=debug
      - --peer=server01:50051
      - --peer=server02:50051
      - --peer=server04:50051
      - --peer=server05:50051
    ports:
      - 50053:50051
  server04:
    image: distribuidos:dev
    build: .
    command:
      - -v=debug
      - --peer=server01:50051
      - --peer=server02:50051
      - --peer=server03:50051
      - --peer=server05:50051
    ports:
      - 50054:50051
  server05:
    image: distribuidos:dev
    build: .
    command:
      - -v=debug
      - --peer=server01:50051
      - --peer=server02:50051
      - --peer=server03:50051
      - --peer=server04:50051
    ports:
      - 50055:50051
